version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: razorpay/razorpay
    versions:
    - 2.5.0
